### PR TITLE
If a reported p-value is less than 2.2e-16 (precise limit), it is dis…

### PR DESCRIPTION
**Pull request by lavenderca**
…played as '< 2.2e-16'

### CODE REVIEW

**Review by shapiromatron — COMMENTED** [review]
Can this be rewritten as a single function named `displayPValue` is a utility function that's used everywhere? 

Perhaps in `utils/helpers.js`?

**Comment by lavenderca** [comment]
Totally.  I'll make the change.

**Comment by lavenderca** [comment]
OK.  Function added.

**Review by shapiromatron — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
